# Generated by Django 4.0.3 on 2022-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('courseNumber', models.IntegerField(max_length=6)),
                ('instructor', models.CharField(blank=True, default='', max_length=25)),
                ('duration', models.FloatField(blank=True, max_length=6)),
            ],
        ),
    ]
