# Generated by Django 4.0.3 on 2022-03-30 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='initialDeposit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkbook.account')),
            ],
            managers=[
                ('transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
